# Avocado Memo — Supporting Calculations

In [23]:
# Import Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [24]:
# Load the two source files
data_2025 = pd.read_csv("2025Data.csv")
data_2026 = pd.read_csv("2026Data.csv")

In [25]:
# Basic check of the source structure
print("2025 shape:", data_2025.shape)
print("2026 shape:", data_2026.shape)
print("Columns:", data_2025.columns.tolist())

2025 shape: (6656, 16)
2026 shape: (4096, 16)
Columns: ['Report', 'Timeframe', 'Period', 'Type', 'Geography', 'Current Year Week Ending', 'ASP Current Year', 'Total Bulk and Bags', '4046', '4225', '4770', 'TotalBagged', 'Sml Bagged', 'Lrg Bagged', 'X-Lrg Bagged', 'Unknown Bag Size']

## 1. 2025 Full-Year Baseline

In [26]:
# Total U.S., all categories, all 52 weeks of 2025
us_2025_full = data_2025[
    (data_2025["Geography"] == "Total U.S.") &
    (data_2025["Period"] <= 52)
].copy()

us_2025_full["Calculated Revenue"] = (
    us_2025_full["Total Bulk and Bags"] *
    us_2025_full["ASP Current Year"]
)

volume_2025_full = us_2025_full["Total Bulk and Bags"].sum()
revenue_2025_full = us_2025_full["Calculated Revenue"].sum()
weighted_asp_2025_full = revenue_2025_full / volume_2025_full

print(f"2025 full-year volume: {volume_2025_full:,.2f}")
print(f"2025 full-year revenue: ${revenue_2025_full:,.2f}")
print(f"2025 full-year weighted ASP: ${weighted_asp_2025_full:.4f}")

2025 full-year volume: 2,986,017,472.42
2025 full-year revenue: $3,494,783,136.99
2025 full-year weighted ASP: $1.1704

## 2. 2025 Week 1-32 Baseline For Comparison

In [27]:
us_2025_ytd = data_2025[
    (data_2025["Geography"] == "Total U.S.") &
    (data_2025["Period"] <= 32)
].copy()

us_2025_ytd["Calculated Revenue"] = (
    us_2025_ytd["Total Bulk and Bags"] *
    us_2025_ytd["ASP Current Year"]
)

volume_2025_ytd = us_2025_ytd["Total Bulk and Bags"].sum()
revenue_2025_ytd = us_2025_ytd["Calculated Revenue"].sum()
weighted_asp_2025_ytd = revenue_2025_ytd / volume_2025_ytd

print(f"2025 Weeks 1–32 volume: {volume_2025_ytd:,.2f}")
print(f"2025 Weeks 1–32 revenue: ${revenue_2025_ytd:,.2f}")
print(f"2025 Weeks 1–32 weighted ASP: ${weighted_asp_2025_ytd:.4f}")

2025 Weeks 1–32 volume: 1,870,698,865.49
2025 Weeks 1–32 revenue: $2,329,302,854.98
2025 Weeks 1–32 weighted ASP: $1.2452

## 3. Key Market Metrics (Week 1-32)

In [28]:
us_2026_ytd = data_2026[
    (data_2026["Geography"] == "Total U.S.") &
    (data_2026["Period"] <= 32)
].copy()

us_2026_ytd["Calculated Revenue"] = (
    us_2026_ytd["Total Bulk and Bags"] *
    us_2026_ytd["ASP Current Year"]
)

volume_2026_ytd = us_2026_ytd["Total Bulk and Bags"].sum()
revenue_2026_ytd = us_2026_ytd["Calculated Revenue"].sum()
weighted_asp_2026_ytd = revenue_2026_ytd / volume_2026_ytd

print(f"2026 Weeks 1–32 total volume: {volume_2026_ytd:,.2f}")
print(f"2026 Weeks 1–32 total revenue: ${revenue_2026_ytd:,.2f}")
print(f"2026 Weeks 1–32 weighted ASP: ${weighted_asp_2026_ytd:.4f}")

2026 Weeks 1–32 total volume: 2,125,800,177.37
2026 Weeks 1–32 total revenue: $2,142,657,308.71
2026 Weeks 1–32 weighted ASP: $1.0079

## 4. 2026 Category Performance Chart

In [29]:
def summarize_type(df):
    result = (
        df.groupby("Type")
          .apply(
              lambda g: pd.Series({
                  "Volume": g["Total Bulk and Bags"].sum(),
                  "Revenue": (
                      g["Total Bulk and Bags"] *
                      g["ASP Current Year"]
                  ).sum()
              }),
              include_groups=False
          )
    )
    result["Weighted ASP"] = result["Revenue"] / result["Volume"]
    return result

type_2026_ytd = summarize_type(us_2026_ytd)

print("\n2026 Weeks 1–32")
display(type_2026_ytd)

2026 Weeks 1–32

                    Volume       Revenue  Weighted ASP
Type
Conventional  2.020685e+09  1.978496e+09      0.979122
Organic       1.051156e+08  1.641609e+08      1.561718

## 6. Bulk Size Growth

In [30]:
plu_columns = ["4046", "4225", "4770"]

plu_summary = pd.DataFrame({
    "2025 Weeks 1–32 Volume": us_2025_ytd[plu_columns].sum(),
    "2026 Weeks 1–32 Volume": us_2026_ytd[plu_columns].sum()
})

plu_summary["2026 Volume"] = plu_summary["2026 Weeks 1–32 Volume"]

display(plu_summary)

      2025 Weeks 1–32 Volume  2026 Weeks 1–32 Volume   2026 Volume
4046            8.671604e+08            8.890511e+08  8.890511e+08
4225            1.972775e+08            2.675278e+08  2.675278e+08
4770            2.394555e+07            4.946765e+07  4.946765e+07

## 7. Bagged Formats

In [31]:
bag_columns = ["TotalBagged", "Sml Bagged", "Lrg Bagged", "X-Lrg Bagged"]

bagged_summary = pd.DataFrame({
    "2025 Weeks 1–32 Volume": us_2025_ytd[bag_columns].sum(),
    "2026 Weeks 1–32 Volume": us_2026_ytd[bag_columns].sum()
})

display(bagged_summary)

              2025 Weeks 1–32 Volume  2026 Weeks 1–32 Volume
TotalBagged             7.823154e+08            9.197537e+08
Sml Bagged              6.768769e+08            7.574343e+08
Lrg Bagged              6.123515e+07            9.632801e+07
X-Lrg Bagged            6.746146e+06            2.126751e+07

## 8. Regional Outliers

In [32]:
regions = ["Southeast", "California", "South Central"]

regional_rows = []

for region in regions:
    region_data = data_2026[
        (data_2026["Geography"] == region) &
        (data_2026["Period"] <= 32)
    ].copy()

    region_data["Calculated Revenue"] = (
        region_data["Total Bulk and Bags"] *
        region_data["ASP Current Year"]
    )

    volume = region_data["Total Bulk and Bags"].sum()
    revenue = region_data["Calculated Revenue"].sum()
    weighted_asp = revenue / volume

    regional_rows.append({
        "Region": region,
        "Volume": volume,
        "Revenue": revenue,
        "Weighted ASP": weighted_asp
    })

regional_summary = pd.DataFrame(regional_rows).set_index("Region")

display(regional_summary)

                     Volume       Revenue  Weighted ASP
Region
Southeast      3.166322e+08  2.838294e+08      0.896401
California     3.364441e+08  3.938956e+08      1.170761
South Central  2.497830e+08  2.107182e+08      0.843605